server:
  port: 8081

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: true

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${SPRING_DATASOURCE_DEMO_URL:${SPRING_DATASOURCE_URL}}
    username: ${SPRING_DATASOURCE_DEMO_USERNAME:${SPRING_DATASOURCE_USERNAME}}
    password: ${SPRING_DATASOURCE_DEMO_PASSWORD:${SPRING_DATASOURCE_PASSWORD}}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        globally_quoted_identifiers: true
    database: postgresql

  flyway:
    enabled: true
    locations:
      - classpath:db/migration/PostgreSQL

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: homepage-order-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "Homepage.practice.*"
        spring.json.value.default.type: Homepage.practice.Event.DTO.OrderPaidEvent

app:
  kafka:
    topics:
      order-paid: order.paid

payment:
  mock:
    base-url: http://localhost:8081/public/mock-payments

logging:
  level:
    root: info
    org.hibernate.SQL: warn
    org.springframework.security: warn
    org.springframework.web: warn
